name: distincter
description: A tool that can check lists in Markdown files and find duplicates.
homepage: https://github.com/fartem/distincter
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  select_annotation: ^0.2.0

dev_dependencies:
  lints: ^2.0.0

  build_runner:
  select: ^0.4.0
